12-11-2022 03:41:14| ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
12-11-2022 03:42:11| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/igry_i_igrushki/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001281CC6A950>, 'Connection to www.detmir.ru timed out. (connect timeout=None)'))
12-11-2022 03:42:37| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/igry_i_igrushki/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001974A51A7A0>, 'Connection to www.detmir.ru timed out. (connect timeout=None)'))
12-12-2022 07:47:00| ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
12-12-2022 07:48:26| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000018309BAE0E0>, 'Connection to www.detmir.ru timed out. (connect timeout=None)'))
12-12-2022 07:56:24| 'list' object has no attribute 'get'
12-12-2022 08:07:27| 'list' object has no attribute 'get'
12-12-2022 08:13:01| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
12-12-2022 08:13:27| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))
12-12-2022 08:17:03| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None)))
12-12-2022 08:24:23| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000295325D18A0>, 'Connection to 54.154.10.13 timed out. (connect timeout=None)'))
12-12-2022 08:24:23| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Temporarily Unavailable')))
12-12-2022 08:24:23| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Temporarily Unavailable')))
12-12-2022 08:24:44| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000295325D2050>, 'Connection to 54.154.10.13 timed out. (connect timeout=None)'))
12-12-2022 08:24:55| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))
12-12-2022 08:24:59| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:25:03| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:25:08| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:28:05| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Service Unavailable')))
12-12-2022 08:28:09| HTTPSConnectionPool(host='www.detmir.ru', port=443): Max retries exceeded with url: /catalog/index/name/lego/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:29:12| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002A16C8619C0>, 'Connection to 54.154.10.13 timed out. (connect timeout=None)'))
12-12-2022 08:30:36| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
12-12-2022 08:33:06| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002144A2DD9F0>, 'Connection to 46.219.80.142 timed out. (connect timeout=None)'))
12-12-2022 08:33:10| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:33:32| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002144A2DE170>, 'Connection to 46.219.80.142 timed out. (connect timeout=None)'))
12-12-2022 08:33:54| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002144A2DEA10>, 'Connection to 46.219.80.142 timed out. (connect timeout=None)'))
12-12-2022 08:33:58| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:34:52| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000221566717E0>, 'Connection to 80.48.119.28 timed out. (connect timeout=None)'))
12-12-2022 08:34:55| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022156671FF0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение')))
12-12-2022 08:34:59| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
12-12-2022 08:34:59| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None)))
12-12-2022 08:35:20| HTTPSConnectionPool(host='biggeek.ru', port=443): Max retries exceeded with url: /catalog/apple-iphone (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000221566727D0>, 'Connection to 46.219.80.142 timed out. (connect timeout=None)'))
